// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAff8tk1yLEqKJ_LfoMVtP1M37fWBC6tO4',
    appId: '1:1050739506682:web:64c3dfeb64ed9858f2b843',
    messagingSenderId: '1050739506682',
    projectId: 'artisianflow',
    authDomain: 'artisianflow.firebaseapp.com',
    storageBucket: 'artisianflow.firebasestorage.app',
    measurementId: 'G-NGPHL1ZJR9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmfeY4Ed4NqpnAEPBngvqiaBOi62bnXE0',
    appId: '1:1050739506682:android:0b110c95a7067d28f2b843',
    messagingSenderId: '1050739506682',
    projectId: 'artisianflow',
    storageBucket: 'artisianflow.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBo5tyJJaTAwnYTgOtbydPo1Q1VheUgtrQ',
    appId: '1:1050739506682:ios:6e82b187e6045fecf2b843',
    messagingSenderId: '1050739506682',
    projectId: 'artisianflow',
    storageBucket: 'artisianflow.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBo5tyJJaTAwnYTgOtbydPo1Q1VheUgtrQ',
    appId: '1:1050739506682:ios:6e82b187e6045fecf2b843',
    messagingSenderId: '1050739506682',
    projectId: 'artisianflow',
    storageBucket: 'artisianflow.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAff8tk1yLEqKJ_LfoMVtP1M37fWBC6tO4',
    appId: '1:1050739506682:web:463d58c0d6e24e3bf2b843',
    messagingSenderId: '1050739506682',
    projectId: 'artisianflow',
    authDomain: 'artisianflow.firebaseapp.com',
    storageBucket: 'artisianflow.firebasestorage.app',
    measurementId: 'G-5KZTSMN3SB',
  );

}